### ISSUE TITLE
zj-80 .ppd question 

### ISSUE THREAD

**Issue by winknudge-tomm** [klirichek/zj-58#1]
Hi,

Not so much an issue but more of a question.

I have a zj-80 thermal printer and have successfully got it working with your filter and .ppd file but am only able to use 58mm of the paper size.

You state in the readme that its PPD is not correct, what was it that you changed in the PPD to resolve the errors? I'm looking to update the zj-80 .ppd so that will work as well.

Thanks very much, I will happily provide my fixed .ppd for the zj-80 if I do manage to resolve the issue.

Tomm

**Comment by klirichek** [comment]
You can get the original filter and compare their ppd with my one.
For now I don't remember the difference exactly, but it was in the settings - the original one incorrect and can't give you the possibility to select different options like logo, space before, space after, etc.
The errors there is in the syntax, so the cups just can't use them.

**Comment by winknudge-tomm** [comment]
Thanks, I got it working on ubuntu 12.04 64 bit using the official filter from the install80 file but used your ppd file as a working template to reconstruct the ZJ-80 version.

For reference it appears to be the lack of settings groupings in the official ppd file that caused the issues. 

*OpenGroup: CutGroup/Cut Options
// options in here
*CloseGroup: *CutGroup

Here is a link to the working ZJ-80 ppd, it also has label cutting enabled.

https://drive.google.com/file/d/0BwXpo6QvBD3VZjUzVzJySkVGQUU/view?usp=sharing

**Comment by klirichek** [comment]
Wow! The names of the options in PPD matches the ones used in .c source.
So, if you used my names, it is just a luck that it works!
(btw - it is possible to modify the filter to support both models, and the cutting also. I also look to support same-looking XP-58 model).
The only need is
1) add the cut command to ppd (that will affect all GUI in all progs)
2) modify the .c source (add the parsing of that ppd option)
3) add support of the cut (escape command for printer). In condition from the option.

**Comment by kazarrugh** [comment]
Thanks for posting these, really grateful. 
I am trying to do this on another thermal printer from POSBANK which is also 80mm.  I tried installing the filter with the zj-80 ppd, but the receipt is only printing on the left 50mm of the page, and leaves the right 30mm blank.  Also the cut is not working. 
I couldn't find the official filter from the install80.

**Comment by klirichek** [comment]
Ensure that filter (file rastertozj) located at `/usr/lib/cups/filter` (usually) has owner/group as root:root, and that chmod 0755

**Comment by YaPaY** [comment]
I downloaded Zijiang ZJ-80v2 driver but cutter doesn't work still

**Comment by jonra1993** [comment]
Maybe you should try this repository. It works for my Zj-80mm printer https://github.com/IntegersOfK/Hoin-POS-58-80
