### ISSUE TITLE
Issue with my 80mm Thermal Printer...

### ISSUE THREAD

**Issue by francoisbouffardtrio** [klirichek/zj-58#12]
Thank you for your work. I try to adapt it to my Excelvan ZJ-8001 80mm. 
I have an issue which has already been mentioned. The printer prints only 58mm of the paper.

I used the modified ZJ-wn80v2.ppd file from tomwarham (thanks to it) but it would seem that in the file rastertozj, there’s a hard-coded reference to 384 dots wide in the driver code: https://github.com/klirichek/zj-58/blob/master/rastertozj.c#L260 and also the PPD appears to be hard-coded for 48 mm printing width.
Can you give me the values ​​that would need to be changed in the file for it to work?
Thank’s. François

**Comment by redfish4ktc** [comment]
We have worked with @francoisbouffardtrio on this and we have been able to make the zj-80 printer work by modifying the rastertozj.c driver

@francoisbouffardtrio can you please post the value modified on line 260 ?

**Comment by francoisbouffardtrio** [comment]
https://github.com/francoisbouffardtrio/ZJ-8001

**Comment by YaPaY** [comment]
finally I can use my 80mm printer with rapsberry. Thanks redfish4ktc and francoisbouffardtrio. I have a just problem so I can't make smaller the texts. The default is too much bigger. If I resize via Linux printer settings these are doesn't affect. It is weird

**Comment by klirichek** [comment]
@francoisbouffardtrio I've updated the driver for both 58 and 80mm models.
(however, I've noticed in your changes that you've forgotten to modify the rest of paper formats; I mean, width in points in .drv).

However now issue is not actual, so I close it. Feel free to reopen if problem still persist
