### ISSUE TITLE
How to compile for macosX

### ISSUE THREAD

**Issue by bot9987** [klirichek/zj-58#15]
Hi,
Could you help with a more detaild instructions on how to compile it fro macosX. I've tried but can't seem to make anything.

**Comment by bot9987** [comment]
Thanks in advance

**Comment by klirichek** [comment]
same as on any other system.
You need dev tools installed.
Then just issue 'make'. .ppd and rastertozj binary you have to place in necessary location on mac (don't know where exactly)

**Comment by blinkythebear** [comment]
After 'make' you can create an easily installable package like this: https://gist.github.com/blinkythebear/860d28107a25ea64b254bb9069ce8eeb
