### ISSUE TITLE
error when trying to complie for OSX

### ISSUE THREAD

**Issue by bot9987** [klirichek/zj-58#16]
hi,
When I try to compile the driver on my OSX 10.11.6 i get this list of warnings and one error can someone please help?

thanks

gcc -Wl,-rpath,/usr/lib -Wall -fPIC -O3 -c rastertozj.c
clang: warning: -Wl,-rpath,/usr/lib: 'linker' input unused
rastertozj.c:109:11: warning: 'ppdFindMarkedChoice' is deprecated: Use
      cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]
        choice = ppdFindMarkedChoice(ppd, choiceName);
                 ^
/usr/include/cups/ppd.h:380:22: note: 'ppdFindMarkedChoice' has been explicitly
      marked deprecated here
extern ppd_choice_t     *ppdFindMarkedChoice(ppd_file_t *ppd,
                         ^
rastertozj.c:113:17: warning: 'ppdFindOption' is deprecated: Use
      cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]
                if ((option = ppdFindOption(ppd, choiceName))          =...
                              ^
/usr/include/cups/ppd.h:383:22: note: 'ppdFindOption' has been explicitly marked
      deprecated here
extern ppd_option_t     *ppdFindOption(ppd_file_t *ppd, const char *keyword)
                         ^
rastertozj.c:114:17: warning: 'ppdFindChoice' is deprecated: Use
      cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]
                if ((choice = ppdFindChoice(option,option->defchoice)) =...
                              ^
/usr/include/cups/ppd.h:378:22: note: 'ppdFindChoice' has been explicitly marked
      deprecated here
extern ppd_choice_t     *ppdFindChoice(ppd_option_t *o, const char *option)
                         ^
rastertozj.c:127:8: warning: 'ppdOpenFile' is deprecated: Use cupsCopyDestInfo
      and friends instead. [-Wdeprecated-declarations]
        ppd = ppdOpenFile(getenv("PPD"));
              ^
/usr/include/cups/ppd.h:392:20: note: 'ppdOpenFile' has been explicitly marked
      deprecated here
extern ppd_file_t       *ppdOpenFile(const char *filename) _PPD_DEPRECATED;
                         ^
rastertozj.c:129:2: warning: 'ppdMarkDefaults' is deprecated: Use
      cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]
        ppdMarkDefaults(ppd);
        ^
/usr/include/cups/ppd.h:387:14: note: 'ppdMarkDefaults' has been explicitly
      marked deprecated here
extern void             ppdMarkDefaults(ppd_file_t *ppd) _PPD_DEPRECATED;
                        ^
rastertozj.c:134:3: warning: 'cupsMarkOptions' is deprecated: Use
      cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]
                cupsMarkOptions(ppd, numOptions, options);
                ^
/usr/include/cups/ppd.h:365:13: note: 'cupsMarkOptions' has been explicitly
      marked deprecated here
extern int              cupsMarkOptions(ppd_file_t *ppd, int num_options,
                        ^
rastertozj.c:145:2: warning: 'ppdClose' is deprecated: Use cupsCopyDestInfo and
      friends instead. [-Wdeprecated-declarations]
        ppdClose(ppd);
        ^
/usr/include/cups/ppd.h:367:14: note: 'ppdClose' has been explicitly marked
      deprecated here
extern void             ppdClose(ppd_file_t *ppd) _PPD_DEPRECATED;
                        ^
rastertozj.c:169:1: error: unknown type name '__sighandler_t'
__sighandler_t old_signal;

**Comment by klirichek** [comment]
Whole PPD Api on Mac is deprecated, this is the reason for warnings.
For the error you can put:
```
#ifndef __sighandler_t
typedef void (*__sighandler_t) (int);
#endif
```

above the line with 169

**Comment by bot9987** [comment]
thanks for the explanation.
But I can not add this above the line with 169 as the text pasted above was generated by using "make" command.

**Comment by klirichek** [comment]
@bot9987 I mean line in `rastertojs.c` file, not in make output

**Comment by bot9987** [comment]
Sorry about that. I've added it but now gets another error:

gcc  -o rastertozj rastertozj.o -lcupsimage -lcups
Undefined symbols for architecture x86_64:
  "_initializeSettings", referenced from:
      _main in rastertozj.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [rastertozj] Error 1

and the new generated file rastertozj.o contains only:
Ïúíþ

Thanks in advance

**Comment by bot9987** [comment]
thanks used the new update and was able to compile. will let you know if it prints.
