### ISSUE TITLE
very narrow print 

### ISSUE THREAD

**Issue by effelle** [klirichek/zj-58#17]
First of all, thanks for this driver!
I'm experiencing a issue with the printable area, much more narrow compared with windows driver.
I'm using the default page size, 58x105mm but I need to reduce a lot in order to have all the information on page. What could be a good parameter for 

`*PageSize X48MMY105MM/58mm x 105mm:         "<</PageSize[136 298]/HWResolution[203 203]/ImagingBBox null>>setpagedevice"

*PageRegion X48MMY105MM/58mm x 105mm:         "<</PageSize[164 298]/HWResolution[203 203]/ImagingBBox null>>setpagedevice"
`

to arquive a larger area?
Thanks!

**Comment by makefu** [comment]
sounds reasonable, i had similar issues with my printer (narrow print). i try to test on my printer

**Comment by klirichek** [comment]
For most of 58-mm POS printers that is not possible.
Thermal head has width of exactly 48mm with 384 points on it.
This is physical limitation, not software-driven.
So, you have 48mm area with 8p/mm resolution, going to ppi it gives 203.2.

**Comment by effelle** [comment]
Then why printed ticket in Windows are wider than on Linux, @klirichek ? 
What I need to change to have a better print?

**Comment by klirichek** [comment]
I think it depends from concrete soft.
When I use default print dialog on a simple prog like 'text edit', or 'notes' (on mac), it permanently assume huge left and right margins (about 2cm), so the printable area in the case just about 1cm.
And I don't know how to override it! However if at the same time I select 'print border' around the label - it is printed using actual physical margins, which are about 5mm from each side of the roll (so whole width of the area is exactly 48mm).
I successfully can fill whole area from LibreOffice Writer - if I set default paper size there as 58mm wide, and set margins to 5mm each side - it uses that very margins, and copies looks perfectly.
You may also try it.

**Comment by effelle** [comment]
Ok, thanks!
