### ISSUE TITLE
Mac OS High Sierra execution

### ISSUE THREAD

**Issue by hongvan0922** [klirichek/zj-58#18]
Hi. I have a X-Printer XP-80, I tried to install this one on my Mac but it show this line:

cp: rastertoxp58: No such file or directory
mkdir: /usr/share/cups/model/xprinter: Operation not permitted
cp: directory /usr/share/cups/model/xprinter does not exist
/Users/macbook
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

I tried the modified file from [this](https://github.com/Zn4rK/xp58/issues), I tried to contact him but no avail. Is there a way to install this driver? Adding to CUPS is not enough, my Mac still said I lacked driver.

**Comment by makefu** [comment]
not sure it was ever meant to work with MacOSX, probably the folders are different. you will most likely need to find out where MacOS cups expects the two files and put them there. restart cups afterwards and it should work.
good luck!

**Comment by hongvan0922** [comment]
The model folder doesn't let me create or copy a new folder. I also tried Root user level, but it didn't work. I can only copy the raster file into filter folder.

**Comment by NicoMaillet** [comment]
It works on Mojave but you have to do it manually.
You need to recompile rastertozj using make.
Then manually copy:
rastertozj to /usr/libexec/cups/filter
and
ZJ-58.ppd to /Library/Printers/PPDs/Contents/Resources

**Comment by klirichek** [comment]
Try latest 'master' branch.
I've added cmake build and added rules especially for mac os

**Comment by klirichek** [comment]
You need to perform 'make install', or 'install' under sudo.
Installation assumes restarting of printing service, and copying files to the system folders. Both are impossible from usual user rights.
