### ISSUE TITLE
Out Of Paper

### ISSUE THREAD

**Issue by hrshadhin** [klirichek/zj-58#2]
Hi,I'm recently use this printer with raspberry-pi. and i used your repo to build driver.  if printer is out of paper then how can i know it. how i get that status from lp or cups? please help me

**Comment by darkterra** [comment]
I am interested to

**Comment by klirichek** [comment]
Most of cheap chinese printers recognized as 'unidirectional'. That is, you can just push data to them, but not receive response.
Since I don't have any device with bidirectional link, I can't try and test the feature.
(fast try with existing one gives expected 'none' result)
