### ISSUE TITLE
Not found this one, "xp58.ppd" files. 

### ISSUE THREAD

**Issue by szTom** [klirichek/zj-58#23]
Not found these two PPD files. 
-  list (APPEND PPDS "${PPDDIR}/xp58.ppd" )
-  list (APPENDPPDS "${PPDDIR}/tm20.ppd" )

I have a printer, the name is "Xprinter", model: XP58IIH.  
Support USB and Bluetooth. 
So I need "xp58.ppd". 
Do you have this one?

**Comment by klirichek** [comment]
All the difference is just cosmetic strings (name of the printer).
So, zj-58 will also work.
*OR* you need `ppdc` compiler, which usually comes in `cups-ppdc` packet.
These ppds will be compiled from .drv file then.

**Comment by makefu** [comment]
@klirichek maybe an overview of the "alternative names" of the zj-58 would be nice to have on the README. I know the chinese resellers can get quite creative here.

**Comment by klirichek** [comment]
@makefu yep, I think something neutral like manufacturer 'Thermal' with models 'POS58' and 'POS80' would be ok.
