### ISSUE TITLE
Printed images are followed by garbage characters

### ISSUE THREAD

**Issue by dixonary** [klirichek/zj-58#5]
Some images produce garbage characters after they are printed with `lp`.

The problem seems to be related to the length of the image in some way - a long image printed "down" the paper produces fewer garbage characters than the same image printed landscape.

The issue is not directly related to size the image itself - the same image scaled up or down will be followed by a proportional amount of garbage. Around 60% of the garbage characters are the U character.

**Comment by dixonary** [comment]
More information which might be useful:

* The garbage is always the same for the same size and orientation of one image; it changes if the image is scaled or rotated.

* Different images of the same size have different garbage.

* More intricate or complex images have a greater variety (and length) of garbage. printing a solid 50x50 block of gray results in 47 U's followed by a T. This information is *not* found inside of the .png file itself.

**Comment by scruss** [comment]
what's the model of your printer? There are many variants, and some don't use exactly the same protocol. Can you print text (via lp and the zj58 driver) successfully?

**Comment by dixonary** [comment]
It's the Zijiang ZJ-5890T. 

Printing text via LP or via cups is always correct with no garbage.

**Comment by choongyouqi** [comment]
I am having the same problem too. it's the subsequent print that having the garbage character.

**Comment by scruss** [comment]
Maybe try the [adafruit/zj-58](https://github.com/adafruit/zj-58) fork. It fixes a minor bug in raster width calculation.

**Comment by adiron** [comment]
I have also experienced this problem

**Comment by risq** [comment]
Same problem for me, but as a workaround I made it work by printing a PDF which contains my image.

**Comment by hrvylein** [comment]
> Maybe try the [adafruit/zj-58](https://github.com/adafruit/zj-58) fork. It fixes a minor bug in raster width calculation.

Adafruits driver doesn't add these characters after printing images.

**Comment by klirichek** [comment]
I've fixed bug with raster calculations (actually full output is rewritten) and problem must dissapear now.
